### ISSUE TITLE
Saner default for `transition-step` with `simple` transition

### ISSUE THREAD

**Issue by demperor-music** [Horus645/swww#90] opened 2023-02-23 23:36 UTC
### When did the issue start?
Since updating to the latest version, a week or two ago. I don't know for sure what the old version i was using was.
### What is the issue?
The **fade-in animation** swww used to have when setting new wallpapers **stopped working** all of a sudden, so i had to change my configs to use **other animations, which seem to work normally**.
When using the command manually, i noticed it gave me an error: `failed to get cache path: failed to create cache_path: No such file or directory (os error 2)`.
### What did i do to try and fix the issue?
Looked up the man pages and saw it would look for cache files in `$XDG_CACHE_HOME/swww` or `$HOME/.cache/swww`. `~/.cache/swww` seemed to not exist so i **made a new folder with the same name: nothing changed**.
I didn't have `XDG_CACHE_HOME` set, so i used **`XDG_CACHE_HOME=~/.cache/ swww img <PATH>`** to fix the issue, which **worked** in the sense that it **stopped giving me the warning about the cache path**, but **still couldn't get the fade-in animation working.**
### System information
- **CPU:** AMD Ryzen 5 4600G with Radeon Graphics (12) @ 3.7GHz
- **GPU:** AMD ATI 30:00.0 Renoir
- **swww:** swww 0.7.2
- **Rust:** rustup 1.25.2-1, rustc 1.67.0
- **Distro:** Arch Linux, 6.1.11-zen
- **WM:** Hyprland 0.21.0beta-2

**Comment by Horus645** [comment] 2023-02-24 14:08
The path warning problem has already been identified and fixed by @max-ishere in issue #86 and PR #88. The problem was a missing `/`.

When you say "fade-in", do you mean the `simple` animation? And by not working, do you mean it just does the transition instantly, or does it leave you with e.g. a black screen?

**Comment by demperor-music** [comment] 2023-02-24 23:46
Yes sorry I meant the `simple` animation-type.
And yes, it just does the animation instantly.

**Comment by weitcis** [comment] 2023-02-25 05:35
same issue here

**Comment by Horus645** [comment] 2023-02-25 13:05
This is very strange. I can't seem to reproduce it here.

The only thing I can think of is that we changed the default value for `--transition-step`. Can you guys try something like `swww img /path/to/img --transition-type simple --transition-step=1` for me?

**Comment by demperor-music** [comment] 2023-02-25 13:28
That seemed to solve it for me. Thanks!

**Comment by flick0** [comment] 2023-02-25 14:26
i think we cud implement bezier curves for `simple` too

**Comment by Horus645** [comment] 2023-02-25 16:18
> i think we cud implement bezier curves for simple too, the default bezier should be smooth enough

I don't know if that's a good idea. That would make `--transition-step` behave differently just for the `simple` transition. I think it would make things confusing.

**Comment by Horus645** [comment] 2023-02-25 16:43
I've made a very small change where `--transition-step` will default to 2 for the `simple` transition. From what I can tell, this will solve the problem @demperor-music and @weitcis were having.

Closing this for now.

**Closed by Horus645** 2023-02-25 16:43 UTC
Labels: enhancement
