### ISSUE TITLE
BUG: error -- failed to create cache_path

### ISSUE THREAD

**Issue by salkin-mada** [Horus645/swww#101] opened 2023-03-13 09:26 UTC
**daemon** is running and is working. 
The following behavior started after a _suspend_ and _wake_.
`❯ swww img random.jpg`
failed to get cache path: failed to create cache_path: No such file or directory (os error 2)

**Comment by Horus645** [comment] 2023-03-16 12:11
This is liked caused by #86. It should be solved in the main branch.

**Comment by Karmak23** [comment] 2023-03-20 11:33
I confirm it is solved in main branch (first installed 0.7.2 on arch then landed here then installed `swww-git` from AUR then everything fine ;-) ).

**Closed** 2023-04-19 20:06 UTC
