### ISSUE TITLE
swww crashes on ultrawide monitor

### ISSUE THREAD

**Issue by joshbtay** [Horus645/swww#106] opened 2023-03-22 23:23 UTC
Any time I plug in my ultrawide monitor, swww crashes. Attempts to restart it are met with the following message:
```
$ swww init
WARNING: socket file /run/user/1000/swww.socket was not deleted when the previous daemon exited
Error: "Failed to receive answer: io error: Connection reset by peer (os error 104)"
```

Some info about the monitor:
```
Monitor DP-1 (ID 1):
	3440x1440@49.987000
	description: LG Electronics LG HDR WQHD 
```
Plugging in other monitors works fine.

**Comment by Horus645** [comment] 2023-04-03 15:39
Hello, this might be fixed in the `main` branch now that #109 was merged. Could you maybe test it again? It should only print a log message saying the cache image is in the wrong size.

**Comment by stottm** [comment] 2023-05-27 15:14
On swww ver 0.7.3. The swww-daemon core dumps when setting 5120x2160 monitor resolution any higher than 2560x1080. 
Reverting Hyprland back to preferred 2560x1080 resolution it is stable.  

Archlinux 6.3.4 kernel 
Hyprland, built from branch master at commit f27873a6f06dc2f87600edb890f3c38298bfb55f  (updating to v0.25.0)
Using https://github.com/SolDoesTech/HyprV4 Hyprland install script & config which utilizes swww.

AMD Ryzen 9 7950X3D 16-Core Processor
NVIDIA GeForce RTX 4090
NVIDIA Driver Version: 530.41.03
Dell UltraSharp 40 Curved WUHD Monitor - U4021QW 5120x2160@60hz
```
coredumpctl info
           PID: 3791 (swww-daemon)
           UID: 1000 (<user>)
           GID: 1000 (<user>)
        Signal: 6 (ABRT)
     Timestamp: Sat 2023-05-27 10:04:31 EDT (45min ago)
  Command Line: swww-daemon
    Executable: /usr/bin/swww-daemon
 Control Group: /user.slice/user-1000.slice/session-2.scope
          Unit: session-2.scope
         Slice: user-1000.slice
       Session: 2
     Owner UID: 1000 (<user>)
       Boot ID: fc45b2e9d4304d89bfb30051840e0e40
    Machine ID: d1a850237fbf4cd3b076b51f4976731f
      Hostname: archlinux
       Storage: /var/lib/systemd/coredump/core.swww-daemon.1000.fc45b2e9d4304d89bfb30051840e0e40.3791.1685196271000000.zst (present)
  Size on Disk: 676.4K
       Message: Process 3791 (swww-daemon) of user 1000 dumped core.
                
                Stack trace of thread 3791:
                #0  0x00007f84450e526c n/a (libc.so.6 + 0x8926c)
                #1  0x00007f8445095a08 raise (libc.so.6 + 0x39a08)
                #2  0x00007f844507e538 abort (libc.so.6 + 0x22538)
                #3  0x000055652c92bb27 n/a (swww-daemon + 0x65b27)
                #4  0x000055652c92bb16 n/a (swww-daemon + 0x65b16)
                #5  0x000055652c96c026 n/a (swww-daemon + 0xa6026)
                #6  0x000055652c96e32b n/a (swww-daemon + 0xa832b)
                #7  0x000055652c96dfa4 n/a (swww-daemon + 0xa7fa4)
                #8  0x000055652c96df06 n/a (swww-daemon + 0xa7f06)
                #9  0x000055652c96def1 n/a (swww-daemon + 0xa7ef1)
                #10 0x000055652c8d3182 n/a (swww-daemon + 0xd182)
                #11 0x000055652c9023e4 n/a (swww-daemon + 0x3c3e4)
                #12 0x000055652c911516 n/a (swww-daemon + 0x4b516)
                #13 0x000055652c8efd13 n/a (swww-daemon + 0x29d13)
                #14 0x000055652c9186ec n/a (swww-daemon + 0x526ec)
                #15 0x00007f844507f850 n/a (libc.so.6 + 0x23850)
                #16 0x00007f844507f90a __libc_start_main (libc.so.6 + 0x2390a)
                #17 0x000055652c8d5d35 n/a (swww-daemon + 0xfd35)
                ELF object binary architecture: AMD x86-64
```

Attached coredump
[coredump.zip](https://github.com/Horus645/swww/files/11582274/coredump.zip)

**Comment by joshua-holmes** [comment] 2023-05-27 21:03
I also have this issue, my screen resolution is 3440x1440@175. It works great when that monitor is not plugged it, for example I have my 1920x1080@60 and 2560x1440@165 monitors plugged in. But as soon as I plug in my ultrawide, I get:
Error: "Failed to receive answer: io error: Connection reset by peer (os error 104)"

**Comment by joshua-holmes** [comment] 2023-05-27 21:38
Update: I fixed it!

After spending hours troubleshooting, I found that when I deleted the cache, swww worked great on my ultrawide. To delete the cache, I did this:
`rm -fr ~/.cache/swww`

I hope this works for others!

**Comment by stottm** [comment] 2023-05-28 04:49
Confirmed, clearing the ~/.cache/swww works and you might need to kill the /run/user/1000/swww.socket potentially after a coredump.  I'll test more tomorrow to see if the cache continues needing to be cleared.  After clearing the cache, I had to reset my wallpaper by triggering swww but then is started working.

**Comment by Horus645** [comment] 2023-07-11 19:03
Hello, if the problem was clearing the cache, I believe this should be solved in the latest release of `swww`. Could anyone please check and confirm it for me (I don't have an ultrawide to test it).

**Comment by joshua-holmes** [comment] 2023-10-17 06:17
I checked and `swww` for sure works on an ultrawide after clearing the cache

**Closed** 2023-11-30 11:24 UTC
Labels: bug
