### ISSUE TITLE
WARNING: socket file /run/user/1000/swww.socket was not deleted when the previous daemon exited 

### ISSUE THREAD

**Issue by LinuxNerdBTW** [Horus645/swww#92] opened 2023-02-25 03:32 UTC
I use wayland/wayfire on Arch , it was working fine with swww-git version , previously using swww from aur was throwing error like cache path not found but after using swww-git version it resolved , it was working fine but when i logout from my Wms using loginctl and logged back it did not start , 
i tried , 
swww init 
but not starting daemon : 
WARNING: socket file /run/user/1000/swww.socket was not deleted when the previous daemon exited
Error: "Failed to receive answer: io error: Connection reset by peer (os error 104)"

throwing this error 
i tried removing swww.socket but not worked .

**Comment by ZizouHuweidi** [comment] 2023-02-25 17:03
I have been having the same error on Arch hyprland

**Comment by GuyLiner** [comment] 2023-02-28 06:19
Same here, although I was able to delete it after logging in

**Comment by FabianTsch** [comment] 2023-03-01 21:31
I had the same issue on Arch Hyprland. I could fix it by removing 
```shell
export XDG_CACHE_HOME=$HOME/.cache
```
from my wrapper. After that I deleted everything in the `.cache/swww` folder and i could set the environment variable again. So I think that some corrupt files in the .cache folder are causing the problem.

**Comment by caretakr** [comment] 2023-03-05 15:05
This issue was popping for me from time to time and stopped when I ran `swww kill` to properly terminate the daemon. In my case it was easy because I'm running via `systemd` so I put it as stop command and the problem goes away.

Removing the cache folder works too, so maybe is some corrupted files like @mentalAdventurer said.

This is what was logged on `systemd` when I tried to run `swww init --no-daemon` when the daemon was not properly terminated.

    mar 05 11:27:11 kratos systemd[952]: Starting swww...
    mar 05 11:27:11 kratos swww[8731]: WARNING: socket file /run/user/1000/swww.socket was not deleted when the previous daemon exited
    mar 05 11:27:11 kratos swww[8733]: 14:27:11 [INFO] (main) Initialization succeeded! Starting main loop...
    mar 05 11:27:11 kratos systemd[952]: Started swww.
    mar 05 11:27:11 kratos swww[8733]: thread 'main' panicked at 'internal error: entered unreachable code: Iterators of zip_eq have different sizes>
    mar 05 11:27:11 kratos swww[8733]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
    mar 05 11:27:12 kratos systemd-coredump[8739]: [🡕] Process 8733 (swww-daemon) of user 1000 dumped core.
                                               
                                               Stack trace of thread 8733:
                                               #0  0x00007fe56bf648ec n/a (libc.so.6 + 0x878ec)
                                               #1  0x00007fe56bf15ea8 raise (libc.so.6 + 0x38ea8)
                                               #2  0x00007fe56beff53d abort (libc.so.6 + 0x2253d)
                                               #3  0x00005574a2851417 n/a (swww-daemon + 0x61417)
                                               #4  0x00005574a2851406 n/a (swww-daemon + 0x61406)
                                               #5  0x00005574a288b626 n/a (swww-daemon + 0x9b626)
                                               #6  0x00005574a288d808 n/a (swww-daemon + 0x9d808)
                                               #7  0x00005574a288d392 n/a (swww-daemon + 0x9d392)
                                               #8  0x00005574a288d2fc n/a (swww-daemon + 0x9d2fc)
                                               #9  0x00005574a288d2d1 n/a (swww-daemon + 0x9d2d1)
                                               #10 0x00005574a27fcf22 n/a (swww-daemon + 0xcf22)
                                               #11 0x00005574a28274ce n/a (swww-daemon + 0x374ce)
                                               #12 0x00005574a2835faf n/a (swww-daemon + 0x45faf)
                                               #13 0x00005574a28169c3 n/a (swww-daemon + 0x269c3)
                                               #14 0x00005574a2817997 n/a (swww-daemon + 0x27997)
                                               #15 0x00005574a283d3d7 n/a (swww-daemon + 0x4d3d7)
                                               #16 0x00007fe56bf00790 n/a (libc.so.6 + 0x23790)
                                               #17 0x00007fe56bf0084a __libc_start_main (libc.so.6 + 0x2384a)
                                               #18 0x00005574a27ff495 n/a (swww-daemon + 0xf495)
                                               ELF object binary architecture: AMD x86-64

**Comment by Lost-Online** [comment] 2023-03-07 22:29
Could you elaborate on what you meant by "...Running via systemd so I put it as stop command and the problem goes away,"? When I run swww-daemon, I get an error message saying that systemd started a coredump and it aborted my sww-daemon. I did recently reinstall, and it didn't change the error.

Also, sidenote that isn't really important. My commands don't work so I run the files themselves with the commands afterward. I spent awhile trying to get them to work but I think I missed a step...

**Comment by caretakr** [comment] 2023-03-08 20:55
@Lost-Online , I believe that you can't run via Systemd yet is because of environment variables not being imported inside Systemd. On my setup, I use a script to export some variables before and after Sway starts. After that, the service gains access to things like DISPLAY, WAYLAND_DISPLAY, SWAYSOCK, etc.

A script to import the variables on Systemd do the trick. Something like this (I run this before starting Sway):

    #!/bin/sh
    
    #
    # Systemd startup
    #
    
    if command -v /usr/bin/dbus-update-activation-environment >/dev/null 2>&1; then
      /usr/bin/dbus-update-activation-environment --systemd \
        EMAIL \
        GDK_BACKEND \
       _JAVA_AWT_WM_NONREPARENTING \
       _JAVA_OPTIONS \
        LANG \
        MOZ_ENABLE_WAYLAND \
        MOZ_USE_XINPUT2 \
        QT_AUTO_SCREEN_SCALE_FACTOR \
        QT_QPA_PLATFORM \
        QT_QPA_PLATFORMTHEME \
        QT_WAYLAND_DISABLE_WINDOWDECORATION \
        QT_STYLE_OVERRIDE \
        TZ \
        XDG_CACHE_HOME \
        XDG_CONFIG_HOME \
        XDG_CONFIG_DIRS \
        XDG_CURRENT_DESKTOP \
        XDG_DATA_HOME \
        XDG_DESKTOP_DIR \
        XDG_DOCUMENTS_DIR \
        XDG_DOWNLOAD_DIR \
        XDG_MUSIC_DIR \
        XDG_PICTURES_DIR \
        XDG_PUBLICSHARE_DIR \
        XDG_SEAT \
        XDG_SESSION_CLASS \
        XDG_SESSION_DESKTOP \
        XDG_SESSION_ID \
        XDG_SESSION_TYPE \
        XDG_STATE_HOME \
        XDG_TEMPLATES_DIR \
        XDG_VIDEOS_DIR \
        XDG_VTNR
    fi

Then, after Sway starts, I put a script at `exec_always` on Sway config to import more variables (these are defined by Sway). Something like this:

    #!/bin/sh
    
    #
    # Systemd startup
    #
    
    while
      [ -z "$WAYLAND_DISPLAY" ] \
        || [ -z "$DISPLAY" ] \
        || [ -z "$SWAYSOCK" ] \
        || [ ! -S "$SWAYSOCK" ]
    do
      sleep 1
    done
    
    if command -v /usr/bin/dbus-update-activation-environment >/dev/null 2>&1; then
      /usr/bin/dbus-update-activation-environment --systemd \
        DISPLAY \
        SWAYSOCK \
        WAYLAND_DISPLAY
    fi

After this second import of environment to Systemd/Dbus, I start my swww-daemon (I use a custom target, `wayland-session.target` to act as semaphore and tell me when Wayland is good to go). This is my swww.service:
    
    [Unit]
    Description=swww
    Documentation=man:swww(1)
    PartOf=graphical-session.target
    Requires=wayland-session.target
    After=wayland-session.target
    OnFailure=notify-failure@%N.service
    
    [Service]
    ExecStart=/usr/bin/swww init --no-daemon
    ExecStartPost=systemctl --user start swww-daemon.target
    ExecStop=/usr/bin/swww kill
    ExecStopPost=systemctl --user stop swww-daemon.target
    Restart=on-failure
    RestartSec=1
    
    [Install]
    WantedBy=wayland-session.target

It works flawless for me. And, on this service, I put the ExecStop like I told on my previous comment to get rid of this bug.

**Comment by LinuxNerdBTW** [comment] 2023-03-09 01:00
it just work on me when i pkill swww and delete its cache file and config file .

**Comment by Horus645** [comment] 2023-04-01 15:55
Note this might be related to #108.

**Comment by Horus645** [comment] 2023-04-03 15:41
Hi everyone, now that #109 was merged, the crash might solved. The daemon should now only print a log message saying the cache image was in the wrong size. If anyone could test it for I'd greatly appreciate it (I can't seem to be able to reproduce it myself)

**Comment by mentalAdventurer** [comment] 2023-04-06 16:32
@Horus645 
I have tried to reproduce it. I recompiled swww-git from the aur and restored the cache files that caused the problem in the first place.
Unfortunately, the error message remains the same.

```sh
WARNING: socket file /run/user/1000/swww.socket was not deleted when the previous daemon exited
Error: "Failed to receive answer: io error: Connection reset by peer (os error 104)"
```

**Comment by xHallaca** [comment] 2023-04-22 20:26
I'm having the same problem

$ swww init
WARNING: socket file /run/user/1000/swww.socket was not deleted when the previous daemon exited
Error: "Failed to receive answer: io error: Connection reset by peer (os error 104)"

$ swww init --no-daemon
[INFO] (main) Initialization succeeded! Starting main loop...
thread 'main' panicked at 'internal error: entered unreachable code: Iterators of zip_eq have different sizes: 2073600, 921600', /home/hallaca/.cache/yay/swww-git/src/swww/utils/src/comp_decomp.rs:207:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Closed** 2023-04-28 10:47 UTC
Labels: bug

**Comment by LinuxNerdBTW** [comment] 2023-04-28 10:48
Setting XDG default cache directory works on arch 
i also did clearing cache dir , and clearing socket file of swww , it works fine for me

**Comment by latipun7** [comment] 2023-04-28 11:56
I have this problem when I am logged out (exit without restart) from Hyprland. Then I logged in with the same user, but the wallpaper is black (no wallpaper). If I try to run daemon manually, this same error warning appeared. 
I already set `XDG_CACHE_HOME`, so I just only delete the socket file on `/run/user/1000/swww.socket` without clearing the cache. After that run daemon and good to go.

That workflow is inconvenient for me, it should clearing socket file when logged out too. Maybe reopen this issue? 🙏 Thank you

**Comment by Horus645** [comment] 2023-04-28 19:01
I am currently rewriting a lot of stuff since sctk 17.0 came out. There's a lot of improvements already, including maybe finally solving our excess memory usage problem. I've also nuked the cache, since it was giving me trouble in this new implementation. So, in all likelihood, this problem will just disappear. 

If you want to try it you can download and compile the `sctk-0.17` branch. Note that, since it is such a big rewrite, some old bugs might resurface. I haven't fully tested it yet, especially with fractional scaling, so keep that in mind.
